<?php

namespace FreelancingWebsiteBundle\Repository;

/**
 * JobPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobPostRepository extends \Doctrine\ORM\EntityRepository
{
}
